apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.env_vars }}
  {{- toYaml . | nindent 2 }}
  {{- end }}