{{ $maxLength := int 64 }}
{{ $serviceNameMaxLength := int (sub (sub $maxLength 1) (len .Values.environment)) }}
{{ $secretName := substr 0 $serviceNameMaxLength .Values.serviceName  }}

{{- if .Values.secrets -}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.serviceSecretName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: {{ .Values.serviceSecretName }}
    type: Opaque
    data:
    {{- range $.Values.secrets }}
    - key: {{ . }}
      objectName: {{ . }}
    {{- end }}
  parameters:
    objects: |
      - objectName: {{ $secretName }}-{{ .Values.environment }}
        objectType: secretsmanager
        jmesPath:
          {{- range $.Values.secrets }}
          - path: {{ . }}
            objectAlias: {{ . }} 
          {{- end }}
{{- end }}