apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sbo-catalog-arm64
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dlopezby93/eks-arm64-poc.git
    targetRevision: main
    path: charts/develop
    helm:
      valueFiles:
        - values.yaml # the main values file
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
